routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return view('auth.login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('employees', 'EmployeeController');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'first_name' , 'last_name', 'address' 
    ];

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use App\Repositories\EmployeeInterface;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    protected $empRepo;

    public function __construct(EmployeeInterface $empRepo)
    {
        $this->empRepo =$empRepo;
    }
   
    public function index()
    {
        $emps = $this->empRepo->getAll();
        //return $this->empRepo->Paginate();
        return view('employee',compact('emps'));
        //dd($emps);
    }

    public function create() {
        return view('create');
    }
    
       
    public function store(Request $request)
    {
        $employees = $this->empRepo->create($request->all());
        return redirect('employees');
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        $emps=Employee::findOrFail($id);
        return view('edit',compact('emps'));
    }

    
    public function update(Request $request, $id)
    {
        //$emps = $request->only(['first_name']);
        $emps =$request->all();
		$this->empRepo->update($id, $emps);
       
		return redirect('employees');
    }

    
    public function destroy($id)
    {
        $this->empRepo->delete($id);
        return redirect('employees');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $users=User::paginate(7);
        return view('home',compact('users'));
    }
}

resources/views/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Employee</div>
                <div class="card-body">
                <form action="/employees" method="post">
                    {{ csrf_field() }}
                <!-- <input type="hidden" name="user_id" value="{{ Auth::user()->id}}"> -->
                <div class="formgroup">
                <label for="first_name">First Name</label>
                <input type="text" name="first_name" class="form-control">
                <label for="last_name">Last Name</label>
                <input type="text" name="last_name" class="form-control">
                <label for="address">Address</label>
                <textarea name="address" class="form-control" cols="30" rows="10"></textarea>
                </div>
                <div class="btnsubmit">
                <input type="submit" class="btn btn-success float-right">
                </div>
                </form>
                </div>
                <div class="card-footer">
				
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Employee</div>
                <div class="card-body">
                <form action="/employees/{{ $emps->id }}" method="post">
                    {{method_field('PUT')}}
                    {{ csrf_field() }}
                <!-- <input type="hidden" name="user_id" value="{{ Auth::user()->id}}"> -->
                <div class="formgroup">
                <label for="first_name">First Name</label>
                <input type="text" name="first_name" value="{{ $emps->first_name }}" class="form-control">
                <label for="last_name">Last Name</label>
                <input type="text" name="last_name" value="{{ $emps->last_name }}" class="form-control">
                <label for="address">Address</label>
                <textarea name="address" class="form-control" cols="30" rows="10">{{ $emps->address }}</textarea>
                </div>
                <div class="btnsubmit">
                <input type="submit" class="btn btn-success float-right">
                </div>
                </form>
                </div>
                <div class="card-footer">
				
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employee.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard - Employee
				<div class="float-right" id="btn-create">
						<a href="{{ route('employees.create')}}" class="btn btn-success">Create</a>
					</div>
				</div>
                
                <div class="card-body">
                <table class="table table-table">
                        <thead>
							<tr>
								<th>First Name</th>
								<th>Last Name</th> 
								<th>Address</th>
                                <th>Created</th>
                                <th>Updated</th>
								<th colspan="2">Action</th>
							</tr>
						</thead>
										   
						<tbody>
							@foreach($emps as $emp)
							<tr>

								<td>{{$emp->first_name}}</td>
								<td>{{$emp->last_name}}</td>
								<td>{{$emp->address}}</td>
								<td>{{$emp->created_at}}</td>
								<td>{{$emp->updated_at}}</td>
								<td><a href="/employees/{{ $emp->id }}/edit" class="btn btn-success btn-sm">
								Edit</a></td>
								<td>
									<form action="/employees/{{ $emp->id }}" method="POST">
										{{ csrf_field() }}
										{{ method_field('DELETE') }}
										<button class="btn btn-danger btn-sm">Delete</button>
									</form>
								</td>
							</tr>
						@endforeach
						</tbody>
				   </table>
                </div>
                <div class="card-footer">
				<div class="pull-right" id="page_link">
						{{ $emps->links() }}
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard - Users</div>

                <div class="card-body">
                <table class="table table-table">
                        <thead>
							<tr>
								<th>Name</th>
								<th>Email Address</th>
                                <th>Created</th>
								<th>Updated</th>
							</tr>
						</thead>
						@foreach($users as $user)
						<tbody>
							<tr>

								<td>{{$user->name}}</td>
								<td>{{$user->email}}</td>
                                <td>{{ $user->created_at}}</td>								
                                <td>{{ $user->updated_at}}</td>
							</tr>

						</tbody>
						@endforeach
					</table>
                </div>
                <div class="card-footer">
				<div class="pull-right" id="page_link">
						{{ $users->links() }}
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Crud Repository</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                Crud Repository
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ url('home') }}"> Registered Users</a>
                                    <a class="dropdown-item" href="{{ url('employees') }}"> Employee</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>